name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Test
        run: |
          echo "Running Tests....."
          go test -v ./...

      - name: Build
        run: |
          echo "Building....."
          go build -v ./...

      - name: Upload a Build Artifact
        run: echo "Uploading Artifact"
        uses: actions/upload-artifact@v3.0.0
        with:
          name: go-github-cli
          path: ./cmd/main/main
          warn: Warning! No file found
